models:
  - name: ResNet-18
    type: Computer Vision (CV)
  - name: VGG-16
    type: Computer Vision (CV)
  - name: Inception v3
    type: Computer Vision
  - name: BERT
    type: Natural Language Processing (NLP)
  - name: GPT-2
    type: Natural Language Processing (NLP)
  - name: Deep Speech 2
    type: Speech
datasets:
  - name: "CIFAR-10"
    type: Computer Vision (CV)
  - name: "Tiny ImageNet"
    type: Computer Vision (CV)
  - name: "Corpus of Linguistic Acceptability (CoLA)"
    type: Natural Language Processing (NLP)
  - name: "Truncated IMDb Large Movie Review Dataset (Truncated IMDb)"
    type: Natural Language Processing (NLP)
  - name: LibriSpeech
    type: Speech